name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7']
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Bundler
        run: |
          gem install bundler -v 1.17.3

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        run: |
          bundle exec rake
